"""
Task definitions. 16 incident scenarios with difficulty levels (easy, medium, hard, expert).
Each task specifies root cause, cascades, red herrings, and grading parameters.
"""

TASKS = {
    "task_cpu_spike": {
        "name": "Auth service CPU hard loop",
        "difficulty": "easy",
        "max_steps": 10,
        "description": "A hot loop in JWT validation is pegging auth-service CPU at 99%.",
        "alert": "ALERT: Login latency p99 > 8s. Auth service CPU at 99%. Users cannot sign in.",
        "fault_service": "auth-service",
        "fault_type": "cpu_spike",
        "red_herrings": [],
        "ideal_steps": 5,
        "cascade_step": None,
        "cascade_service": None,
        "cascade_fault": None,
    },
    "task_db_connection_leak": {
        "name": "Database connection pool exhaustion",
        "difficulty": "medium",
        "max_steps": 15,
        "description": "Connection pool leak in order-service causing cascading failures.",
        "alert": "ALERT: Database connection timeouts. Order creation failing 100%. Latency spiking.",
        "fault_service": "order-service",
        "fault_type": "connection_pool_exhausted",
        "red_herrings": ["postgres-db"],
        "ideal_steps": 6,
        "cascade_step": 9,
        "cascade_service": "api-gateway",
        "cascade_fault": "upstream_timeout",
    },
    "task_redis_memory_eviction": {
        "name": "Redis cache memory eviction cascade",
        "difficulty": "medium",
        "max_steps": 15,
        "description": "Redis memory threshold hit, evicting keys. Cache hit rate collapsing.",
        "alert": "ALERT: Cache miss rate 89%. redis-cache evicting keys. Session data loss. API latency 5000ms+.",
        "fault_service": "redis-cache",
        "fault_type": "memory_eviction",
        "red_herrings": ["api-gateway"],
        "ideal_steps": 5,
        "cascade_step": 9,
        "cascade_service": "order-service",
        "cascade_fault": "downstream_victim",
    },
    "task_api_rate_limit": {
        "name": "API rate limit misconfiguration",
        "difficulty": "medium",
        "max_steps": 15,
        "description": "Rate limiter threshold set too low, blocking legitimate traffic.",
        "alert": "ALERT: 429 Too Many Requests from api-gateway. Traffic being throttled. User impact increasing.",
        "fault_service": "api-gateway",
        "fault_type": "rate_limit_exceeded",
        "red_herrings": ["order-service"],
        "ideal_steps": 6,
        "cascade_step": 9,
        "cascade_service": "auth-service",
        "cascade_fault": "rate_limit_victim",
    },
    "task_deadlock_order_service": {
        "name": "Database deadlock in order-service",
        "difficulty": "medium",
        "max_steps": 15,
        "description": "Concurrent order transactions causing PostgreSQL deadlock.",
        "alert": "ALERT: Database deadlock detected. orders_db throwing deadlock errors. Transactions rolling back.",
        "fault_service": "postgres-db",
        "fault_type": "deadlock",
        "red_herrings": ["order-service"],
        "ideal_steps": 6,
        "cascade_step": 9,
        "cascade_service": "notification-service",
        "cascade_fault": "connection_exhausted",
    },
    "task_ssl_cert_expired": {
        "name": "TLS certificate expiration",
        "difficulty": "medium",
        "max_steps": 15,
        "description": "SSL certificate for api-gateway expired, causing TLS handshake failures.",
        "alert": "ALERT: TLS handshake failures on api-gateway. x509 certificate expired 3 days ago.",
        "fault_service": "api-gateway",
        "fault_type": "cert_expired",
        "red_herrings": [],
        "ideal_steps": 4,
        "cascade_step": 9,
        "cascade_service": "auth-service",
        "cascade_fault": "handshake_victim",
    },
    "task_slow_query_postgres": {
        "name": "Slow PostgreSQL query degradation",
        "difficulty": "medium",
        "max_steps": 15,
        "description": "Missing database index causing full table scan on high-traffic query.",
        "alert": "ALERT: postgres-db query latency 8000ms+. Sequential scan on large table. order-service timing out.",
        "fault_service": "postgres-db",
        "fault_type": "slow_query",
        "red_herrings": ["order-service"],
        "ideal_steps": 6,
        "cascade_step": 9,
        "cascade_service": "notification-service",
        "cascade_fault": "query_timeout_victim",
    },
    "task_auth_service_500": {
        "name": "Auth service internal server error",
        "difficulty": "medium",
        "max_steps": 15,
        "description": "Null pointer exception in auth token validation handler.",
        "alert": "ALERT: auth-service returning 500 errors. Token validation failing. Login completely down.",
        "fault_service": "auth-service",
        "fault_type": "null_pointer",
        "red_herrings": [],
        "ideal_steps": 5,
        "cascade_step": 9,
        "cascade_service": "order-service",
        "cascade_fault": "auth_timeout_victim",
    },
    "task_k8s_pod_crashloop": {
        "name": "Kubernetes pod crash loop",
        "difficulty": "medium",
        "max_steps": 15,
        "description": "notification-service pod in crash loop due to unhandled exception.",
        "alert": "ALERT: notification-service pod crashing (exit code 1). Crash loop detected. Email notifications blocked.",
        "fault_service": "notification-service",
        "fault_type": "crash_loop",
        "red_herrings": [],
        "ideal_steps": 5,
        "cascade_step": 9,
        "cascade_service": "api-gateway",
        "cascade_fault": "notification_unavailable_victim",
    },
    "task_disk_full": {
        "name": "Disk full — postgres WAL overflow",
        "difficulty": "easy",
        "max_steps": 10,
        "description": "The database WAL log grew unbounded. Disk hit 100% — all INSERT/UPDATE fail with ENOSPC.",
        "alert": "ALERT: postgres-db disk at 100%. WAL at 48GB. All write operations failing with ENOSPC.",
        "fault_service": "postgres-db",
        "fault_type": "disk_full",
        "red_herrings": [],
        "ideal_steps": 4,
        "cascade_step": None,
        "cascade_service": None,
        "cascade_fault": None,
    },
    "task_memory_leak": {
        "name": "Memory leak — notification service GC pauses",
        "difficulty": "medium",
        "max_steps": 15,
        "description": "Memory leak in email template renderer. GC pauses now take 10+ seconds.",
        "alert": "ALERT: notification-service heap at 98%. GC pauses >11s. Email delivery stalling. API timeouts cascading.",
        "fault_service": "notification-service",
        "fault_type": "memory_leak",
        "red_herrings": [],
        "ideal_steps": 6,
        "cascade_step": 9,
        "cascade_service": "api-gateway",
        "cascade_fault": "upstream_timeout",
    },
    "task_thread_starvation": {
        "name": "Thread pool exhaustion — auth service OAuth sync calls",
        "difficulty": "medium",
        "max_steps": 15,
        "description": "New OAuth integration added synchronous HTTP calls inside auth-service request handler.",
        "alert": "ALERT: auth-service thread pool at 100% (200/200 active). Login latency 30s+. OAuth timeout cascade detected.",
        "fault_service": "auth-service",
        "fault_type": "thread_pool_exhausted",
        "red_herrings": [],
        "ideal_steps": 6,
        "cascade_step": 9,
        "cascade_service": "order-service",
        "cascade_fault": "auth_timeout_victim",
    },
    "task_canary_poison": {
        "name": "Canary misconfiguration — api-gateway v2.1 strips auth headers",
        "difficulty": "hard",
        "max_steps": 20,
        "description": "A canary deployment of api-gateway v2.1 receives 10% of traffic and strips the Authorization header.",
        "alert": "ALERT: 10% of requests returning 401 Unauthorized. Canary deployment v2.1 detected. Authorization header missing on canary traffic.",
        "fault_service": "api-gateway",
        "fault_type": "canary_misconfiguration",
        "red_herrings": ["order-service", "auth-service"],
        "ideal_steps": 5,
        "cascade_step": 6,
        "cascade_service": "order-service",
        "cascade_fault": "canary_victim",
    },
    "task_clock_skew": {
        "name": "Clock skew — auth service NTP drift causes token rejections",
        "difficulty": "hard",
        "max_steps": 20,
        "description": "NTP daemon on auth-service host killed. Auth-service clock drifted 8 minutes ahead.",
        "alert": "ALERT: 25% of requests returning 401 from order-service. Cache miss rate 68%. JWT iat timestamps in future. Clock skew suspected.",
        "fault_service": "auth-service",
        "fault_type": "clock_skew",
        "red_herrings": ["redis-cache", "order-service"],
        "ideal_steps": 6,
        "cascade_step": 6,
        "cascade_service": "redis-cache",
        "cascade_fault": "token_cache_miss",
    },
    "task_expert": {
        "name": "Multi-root-cause: Redis + Auth config failure",
        "difficulty": "expert",
        "max_steps": 25,
        "description": (
            "Two independent failures: Redis connection pool exhausted "
            "AND auth-service misconfigured after canary deploy. Both must be identified."
        ),
        "alert": (
            "ALERT: Login failures 62%. Order completions 0%. "
            "On-call paged. Multiple cascading signals."
        ),
        "fault_service": "redis-cache",
        "fault_type": "connection_pool_exhausted",
        "fault_service_2": "auth-service",
        "fault_type_2": "bad_deployment",
        "red_herrings": ["order-service", "notification-service"],
        "ideal_steps": 12,
        "cascade_step": 8,
        "cascade_service": "api-gateway",
        "cascade_fault": "upstream_overload",
    },
    "task_expert_long_horizon": {
        "name": "Long-horizon cascade: Query degradation with latent secondary fault",
        "difficulty": "expert",
        "max_steps": 50,
        "description": (
            "LONG-HORIZON TEST (50 steps). postgres-db slow_query causes gradual degradation. "
            "Quick restart (step ~10) seems to fix it, but introduces a secondary bug in the query planner. "
            "At step 35+, a cascade triggers in order-service. Agent must track state over extended episode, "
            "detect the secondary fault, and implement the correct fix. Tests if agent avoids jumping to "
            "quick conclusions and maintains context across 50-step trajectory."
        ),
        "alert": (
            "ALERT: Order creation latency p99: 500ms → 2000ms → 8000ms (steadily worsening). "
            "postgres-db query time spiking. Partial order backlog forming."
        ),
        "fault_service": "postgres-db",
        "fault_type": "slow_query",
        "fault_service_2": None,
        "fault_type_2": None,
        "red_herrings": ["api-gateway", "redis-cache"],
        "ideal_steps": 25,
        "cascade_step": 35,
        "cascade_service": "order-service",
        "cascade_fault": "downstream_timeout",
    },
}
